@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE4OTM4MjA5fQ.J1YDRM1sTw8MVPMmWl6lsxaAGRaUIUPXNNQGokaoybo

### Crear un nuevo usuario
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "password": "securepassword",
  "active": true
}

### Iniciar sesión (para obtener el token)
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "securepassword"
}

### Crear un nuevo Objetivo
POST {{baseUrl}}/objectives
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "target_amount": 2000,
  "objective_name": "Objetivo de prueba 2",
  "current_amount": 0,
  "icon_name": "icon.png",
  "color_name": "red",
  "start_date": "2024-06-20",
  "deadline": "2024-12-31",
  "currencyTypeId": 1
}

### Obtener todos los Objetivos del Usuario
GET {{baseUrl}}/objectives
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener un Objetivo por id
GET {{baseUrl}}/objectives/1
Content-Type: application/json
Authorization: Bearer {{token}}

### Actualizar un Objetivo por id
PUT {{baseUrl}}/objectives/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "target_amount": 2000
}

### Eliminar un Objetivo por id
DELETE {{baseUrl}}/objectives/2
Content-Type: application/json
Authorization: Bearer {{token}}

### Eliminar todos los Objetivos del Usuario
DELETE {{baseUrl}}/objectives
Content-Type: application/json
Authorization: Bearer {{token}}

### Agregar monto al Objetivo por id
PATCH {{baseUrl}}/objectives/1/monto
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "monto": 100
}

### Ver el progreso de un Objetivo por id
GET {{baseUrl}}/objectives/1/progreso
Content-Type: application/json
Authorization: Bearer {{token}}

