### Crear un nuevo usuario
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "password": "securepassword",
  "active": true
}

### Iniciar sesión (para obtener el token)
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "securepassword"
}

### Crear un nuevo objetivo
POST http://localhost:3000/api/objectives
Content-Type: application/json

{
  "amount": 5000,
  "start_date": "2024-06-01",
  "deadline": "2024-12-31",
  "userId": 1,
  "currencyTypeId": 1,
  "icon_name": "objective-icon",
  "color_name": "blue"
}

### Obtener todos los objetivos
GET http://localhost:3000/api/objectives

### Editar objetivo
PUT http://localhost:3000/api/objectives/1
Content-Type: application/json

{
  "amount": 1200,
  "start_date": "2024-06-01",
  "deadline": "2024-12-31",
  "userId": 1,
  "currencyTypeId": 1,
  "icon_name": "objective-icon",
  "color_name": "red"
}

### Borrar objetivo
DELETE http://localhost:3000/api/objectives/1

### Crear nueva categoria
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Comida",
    "description": "Gastos relacionados con la alimentación",
    "icon_name": "food-icon"
}

### Obtener todas las categorías
GET http://localhost:3000/api/categories

### Obtener una categoría por su ID
GET http://localhost:3000/api/categories/1

### Actualizar una categoría por su ID
PUT http://localhost:3000/api/categories/3
Content-Type: application/json

{
    "name": "Nueva comida",
    "description": "Gastos relacionados con la alimentación actualizada",
    "icon_name": "updated-food-icon"
}

### Eliminar una categoría por su ID
DELETE http://localhost:3000/api/categories/3
